version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - monitoring
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
       - ./.env.dev
    ports:
      - 5432:5432
    networks:
      - monitoring
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static/:/usr/share/nginx/html/static/
      - ./app/media/:/usr/share/nginx/html/media/
    ports:
      - 80:80
    depends_on:
      - django
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring



volumes:
  postgres_data:

networks:
  monitoring: